/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {


@Test(timeout = 4000)
public void test05() throws Throwable {
    Line line0 = new Line();
    line0.setTextElements((List<TextChunk>) null);
    List<TextChunk> list0 = line0.getTextElements();
    assertNull(list0);
}


@Test(timeout = 4000)
public void test00() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = new TextChunk(236.93358F, 0.0F, 0.0F, 0.0F);
    List<TextChunk> list0 = textChunk0.squeeze((Character) null, 339);
    line0.setTextElements(list0);
    line0.addTextChunk(textChunk0);
    line0.addTextChunk(0, textChunk0);
    assertEquals(236.93358F, line0.height, 0.01F);
}


@Test(timeout = 4000)
public void test04() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = new TextChunk((-588.74023F), (-2790.2083F), (-1.0F), 0.3F);
    line0.addTextChunk(textChunk0);
    Character character0 = Character.valueOf('\"');
    Line.removeRepeatedCharacters(line0, character0, (-936));
    assertEquals(0.3F, line0.height, 0.01F);
    assertEquals((-588.4402343630791), line0.getMaxY(), 0.01);
}


@Test(timeout = 4000)
public void test13() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = TextChunk.EMPTY;
    line0.addTextChunk(0, textChunk0);
    String string0 = line0.toString();
    assertEquals("technology.tabula.Line[x=0.0,y=0.0,w=0.0,h=0.0,bottom=0.000000,right=0.000000,chunks='', ]", string0);
}

}
