/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:56:04 GMT 2024
 */
package technology.tabula;


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.PageDims;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class PageDims_ESTest extends PageDims_ESTest_scaffolding {


@Test(timeout = 4000)
public void test05() throws Throwable {
    PageDims pageDims0 = PageDims.of((-2962.7F), (-2962.7F), 275.9F, 477.6F);
    float float0 = pageDims0.getLeft();
    assertEquals(477.6F, pageDims0.getHeight(), 0.01F);
    assertEquals((-2962.7F), pageDims0.getTop(), 0.01F);
    assertEquals(275.9F, pageDims0.getWidth(), 0.01F);
    assertEquals((-2962.7F), float0, 0.01F);
}

}
