/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {


@Test(timeout = 4000)
public void test02() throws Throwable {
    RectangularTextContainer<RectangularTextContainer<TextElement>> rectangularTextContainer0 = new RectangularTextContainer<RectangularTextContainer<TextElement>>((-1.0F), (-1.0F), (-1.0F), (-1.0F));
    RectangularTextContainer<RectangularTextContainer<TextElement>> rectangularTextContainer1 = rectangularTextContainer0.merge(rectangularTextContainer0);
    assertEquals(1.0F, rectangularTextContainer1.width, 0.01F);
}


@Test(timeout = 4000)
public void test15() throws Throwable {
    RectangularTextContainer<RectangularTextContainer<TextElement>> rectangularTextContainer0 = new RectangularTextContainer<RectangularTextContainer<TextElement>>(0.0F, 0.0F, 0.0F, 0.0F);
    // Undeclared exception!
    try {
        rectangularTextContainer0.toString();
        fail("Expecting exception: UnsupportedOperationException");
    } catch (UnsupportedOperationException e) {
        // 
        // no message in exception (getMessage() returned null)
        // 
        verifyException("technology.tabula.RectangularTextContainer", e);
    }
}


@Test(timeout = 4000)
public void test03() throws Throwable {
    TextChunk textChunk0 = TextChunk.EMPTY;
    textChunk0.setTextElements((List<TextElement>) null);
    List<TextElement> list0 = textChunk0.getTextElements();
    assertNull(list0);
}


@Test(timeout = 4000)
public void test05() throws Throwable {
    TextChunk textChunk0 = new TextChunk((-2372.5F), (-2372.5F), 0.0F, 0.0F);
    String string0 = textChunk0.getText(false);
    assertEquals("", string0);
}


@Test(timeout = 4000)
public void test10() throws Throwable {
    RectangularTextContainer<RectangularTextContainer<TextElement>> rectangularTextContainer0 = new RectangularTextContainer<RectangularTextContainer<TextElement>>(1.0F, 0.0F, 0.0F, 1.0F);
    // Undeclared exception!
    try {
        rectangularTextContainer0.getText();
        fail("Expecting exception: UnsupportedOperationException");
    } catch (UnsupportedOperationException e) {
        // 
        // no message in exception (getMessage() returned null)
        // 
        verifyException("technology.tabula.RectangularTextContainer", e);
    }
}

}
