/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:10:49 GMT 2024
 */

package org.jinstagram.entity.relationships;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.relationships.RelationshipData;
import org.jinstagram.entity.relationships.RelationshipFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RelationshipFeed_ESTest extends RelationshipFeed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      Meta meta0 = new Meta();
      relationshipFeed0.setMeta(meta0);
      Meta meta1 = relationshipFeed0.getMeta();
      assertEquals(0, meta1.getCode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      Meta meta0 = new Meta();
      meta0.setCode(2470);
      relationshipFeed0.setMeta(meta0);
      Meta meta1 = relationshipFeed0.getMeta();
      assertEquals(2470, meta1.getCode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      RelationshipData relationshipData0 = new RelationshipData();
      relationshipData0.setTargetUserPrivate(true);
      relationshipFeed0.setData(relationshipData0);
      RelationshipData relationshipData1 = relationshipFeed0.getData();
      assertTrue(relationshipData1.isTargetUserPrivate());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      RelationshipData relationshipData0 = relationshipFeed0.getData();
      assertNull(relationshipData0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      Meta meta0 = relationshipFeed0.getMeta();
      assertNull(meta0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      String string0 = relationshipFeed0.toString();
      assertEquals("RelationshipFeed [data=null, meta=null]", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      RelationshipData relationshipData0 = new RelationshipData();
      relationshipFeed0.setData(relationshipData0);
      RelationshipData relationshipData1 = relationshipFeed0.getData();
      assertNull(relationshipData1.getOutgoingStatus());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RelationshipFeed relationshipFeed0 = new RelationshipFeed();
      Meta meta0 = new Meta();
      relationshipFeed0.setMeta(meta0);
      meta0.setCode((-924));
      Meta meta1 = relationshipFeed0.getMeta();
      assertEquals((-924), meta1.getCode());
  }
}
