/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:31:38 GMT 2024
 */

package com.zappos.json.format;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.BigDecimalFormatter;
import com.zappos.json.format.ValueFormatter;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BigDecimalFormatter_ESTest extends BigDecimalFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      BigDecimal bigDecimal0 = bigDecimalFormatter0.parse((ZapposJson) null, "0");
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      ZapposJson zapposJson0 = ZapposJson.getInstance("");
      BigDecimal bigDecimal0 = bigDecimalFormatter0.parse(zapposJson0, "10");
      assertEquals((short)10, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      BigDecimal bigDecimal0 = bigDecimalFormatter0.cast((Object) null);
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      BigDecimal bigDecimal1 = bigDecimalFormatter0.cast(bigDecimal0);
      assertSame(bigDecimal0, bigDecimal1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BigDecimal bigDecimal0 = new BigDecimal((-2362.417));
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      BigDecimal bigDecimal1 = bigDecimalFormatter0.cast(bigDecimal0);
      assertEquals((short) (-2362), bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      ZapposJson zapposJson0 = ZapposJson.getInstance("X4");
      try { 
        bigDecimalFormatter0.parse(zapposJson0, "[");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      try { 
        bigDecimalFormatter0.parse((ZapposJson) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      ZapposJson zapposJson0 = ZapposJson.getInstance();
      // Undeclared exception!
      try { 
        bigDecimalFormatter0.format(zapposJson0, (BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.zappos.json.format.BigDecimalFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      // Undeclared exception!
      try { 
        bigDecimalFormatter0.cast(bigDecimalFormatter0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      ZapposJson zapposJson0 = ZapposJson.getInstance("");
      BigDecimal bigDecimal0 = bigDecimalFormatter0.parse(zapposJson0, "-2362.41699999999991632648743689060211181640625");
      assertEquals((short) (-2362), bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      ZapposJson zapposJson0 = ZapposJson.getInstance("");
      BigDecimal bigDecimal0 = new BigDecimal((-2362.417));
      String string0 = bigDecimalFormatter0.format(zapposJson0, bigDecimal0);
      assertEquals("-2362.41699999999991632648743689060211181640625", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      ValueFormatter<BigDecimal> valueFormatter0 = bigDecimalFormatter0.newInstance();
      assertNotSame(bigDecimalFormatter0, valueFormatter0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BigDecimalFormatter bigDecimalFormatter0 = new BigDecimalFormatter();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      BigDecimal bigDecimal1 = bigDecimalFormatter0.cast(bigDecimal0);
      assertSame(bigDecimal1, bigDecimal0);
  }
}
