/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:32:23 GMT 2024
 */

package org.jinstagram.entity.users.feed;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.users.feed.UserFeed;
import org.jinstagram.entity.users.feed.UserFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserFeed_ESTest extends UserFeed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      LinkedList<UserFeedData> linkedList0 = new LinkedList<UserFeedData>();
      UserFeedData userFeedData0 = new UserFeedData();
      userFeed0.setUserList(linkedList0);
      linkedList0.offerLast(userFeedData0);
      List<UserFeedData> list0 = userFeed0.getUserList();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      Pagination pagination0 = new Pagination();
      userFeed0.setPagination(pagination0);
      Pagination pagination1 = userFeed0.getPagination();
      assertNull(pagination1.getNextMaxTagId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      Meta meta0 = new Meta();
      userFeed0.setMeta(meta0);
      Meta meta1 = userFeed0.getMeta();
      assertNull(meta1.getErrorMessage());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      Meta meta0 = new Meta();
      meta0.setCode(841);
      userFeed0.setMeta(meta0);
      Meta meta1 = userFeed0.getMeta();
      assertNull(meta1.getErrorType());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      Pagination pagination0 = userFeed0.getPagination();
      assertNull(pagination0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      LinkedList<UserFeedData> linkedList0 = new LinkedList<UserFeedData>();
      userFeed0.setUserList(linkedList0);
      List<UserFeedData> list0 = userFeed0.getUserList();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      String string0 = userFeed0.toString();
      assertEquals("UserFeed [meta=null, pagination=null, userList=null]", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      List<UserFeedData> list0 = userFeed0.getUserList();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      Meta meta0 = new Meta();
      userFeed0.setMeta(meta0);
      meta0.setCode((-1));
      Meta meta1 = userFeed0.getMeta();
      assertSame(meta1, meta0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      UserFeed userFeed0 = new UserFeed();
      Meta meta0 = userFeed0.getMeta();
      assertNull(meta0);
  }
}
