/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:59:46 GMT 2024
 */

package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Page;
import technology.tabula.ProjectionProfile;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ProjectionProfile_ESTest extends ProjectionProfile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      float[] floatArray0 = new float[9];
      floatArray0[7] = (-5096.423F);
      float[] floatArray1 = ProjectionProfile.getFirstDeriv(floatArray0);
      assertArrayEquals(new float[] {0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, (-5096.423F), 0.0F, 5096.423F}, floatArray1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      float[] floatArray0 = new float[9];
      floatArray0[0] = 995.3F;
      float[] floatArray1 = ProjectionProfile.getFirstDeriv(floatArray0);
      assertArrayEquals(new float[] {(-995.3F), (-995.3F), 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F}, floatArray1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      float[] floatArray0 = new float[7];
      floatArray0[0] = (-93.946F);
      floatArray0[1] = (-796.6174F);
      float[] floatArray1 = ProjectionProfile.getAutocorrelation(floatArray0);
      assertArrayEquals(new float[] {0.0F, 748.39014F, -0.0F, 0.0F, 0.0F, 0.0F}, floatArray1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      float[] floatArray0 = new float[7];
      floatArray0[0] = (-418.7F);
      float[] floatArray1 = ProjectionProfile.filter(floatArray0, 1905.514F);
      assertArrayEquals(new float[] {(-418.7F), 797420.06F, (-1.51869773E9F), 2.89238129E12F, (-5.5085812E15F), 1.049117E19F, (-1.9980582E22F)}, floatArray1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      float[] floatArray0 = new float[2];
      floatArray0[0] = 3035.0F;
      float[] floatArray1 = ProjectionProfile.smooth(floatArray0, 3929);
      assertArrayEquals(new float[] {0.0F, 0.0F}, floatArray1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      float[] floatArray0 = new float[6];
      float[] floatArray1 = ProjectionProfile.smooth(floatArray0, (-722));
      assertArrayEquals(new float[] {-0.0F, -0.0F, -0.0F, -0.0F, -0.0F, -0.0F}, floatArray1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      float[] floatArray0 = new float[1];
      float[] floatArray1 = ProjectionProfile.getAutocorrelation(floatArray0);
      assertEquals(0, floatArray1.length);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        ProjectionProfile.smooth((float[]) null, (-186));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        ProjectionProfile.getFirstDeriv((float[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      float[] floatArray0 = new float[1];
      // Undeclared exception!
      try { 
        ProjectionProfile.getFirstDeriv(floatArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        ProjectionProfile.getAutocorrelation((float[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      float[] floatArray0 = new float[0];
      // Undeclared exception!
      try { 
        ProjectionProfile.getAutocorrelation(floatArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        ProjectionProfile.filter((float[]) null, 0.0F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      float[] floatArray0 = new float[0];
      // Undeclared exception!
      try { 
        ProjectionProfile.filter(floatArray0, 0.0F);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Rectangle> linkedList0 = new LinkedList<Rectangle>();
      ProjectionProfile projectionProfile0 = null;
      try {
        projectionProfile0 = new ProjectionProfile((Page) null, linkedList0, (-102.2418F), (-102.2418F));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("technology.tabula.ProjectionProfile", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      float[] floatArray0 = new float[0];
      float[] floatArray1 = ProjectionProfile.smooth(floatArray0, (-627));
      assertNotSame(floatArray1, floatArray0);
  }
}
