// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/UserFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:32:23 GMT 2024
 */
package org.jinstagram.entity.users.feed;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.users.feed.UserFeed;
import org.jinstagram.entity.users.feed.UserFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class UserFeed_ESTest extends UserFeed_ESTest_scaffolding {
    @Test
    public void testToString() {
        UserFeed userFeed = new UserFeed();
        
        Meta meta = new Meta();
        meta.setCode(200);
        meta.setErrorType("none");
        userFeed.setMeta(meta);
        
        Pagination pagination = new Pagination();
        pagination.setNextUrl("https://nextpage.com");
        pagination.setNextMaxId("12345");
        userFeed.setPagination(pagination);
        
        List<UserFeedData> userList = new ArrayList<>();
        UserFeedData user1 = new UserFeedData();
        user1.setId("1");
        user1.setUsername("user1");
        userList.add(user1);
        
        UserFeedData user2 = new UserFeedData();
        user2.setId("2");
        user2.setUsername("user2");
        userList.add(user2);
        
        userFeed.setUserList(userList);
        
        String expected = "UserFeed [meta=Meta{code=200, errorType='none'}, pagination=Pagination{nextUrl='https://nextpage.com', nextMaxId='12345'}, userList=[UserFeedData{id='1', username='user1'}, UserFeedData{id='2', username='user2'}]]";
        String actual = userFeed.toString();
        
        assertEquals(expected, actual);
    }
}
