// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagInfoData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:12:33 GMT 2024
 */
package org.jinstagram.entity.tags;


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.tags.TagInfoData;
import org.junit.runner.RunWith;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.tags.TagInfoData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagInfoData_ESTest extends TagInfoData_ESTest_scaffolding {

@Test
public void testToString() {
    // Create a TagInfoData object with test values
    TagInfoData tagInfoData = new TagInfoData();
    tagInfoData.setMediaCount(10);
    tagInfoData.setTagName("Test Tag");

    // Call the toString() method
    String result = tagInfoData.toString();

    // Verify the result
    String expected = "TagInfoData [mediaCount=10, tagName=Test Tag]";
    assertEquals(expected, result);
}

    @Test
    public void testSetMediaCount() {
        TagInfoData tagInfoData = new TagInfoData();
        long mediaCount = 10;
        tagInfoData.setMediaCount(mediaCount);
        assertEquals(mediaCount, tagInfoData.getMediaCount());
    }

    @Test
    public void testGetMediaCount() {
        // Create an instance of TagInfoData
        TagInfoData tagInfoData = new TagInfoData();

        // Set the media count
        long mediaCount = 10;
        tagInfoData.setMediaCount(mediaCount);

        // Call the getMediaCount() method
        long result = tagInfoData.getMediaCount();

        // Assert that the returned value is equal to the set media count
        assertEquals(mediaCount, result);
    }

    @Test
    public void testSetTagName() {
        TagInfoData tagInfoData = new TagInfoData();
        String tagName = "Test Tag";
        
        tagInfoData.setTagName(tagName);
        
        assertEquals(tagName, tagInfoData.getTagName());
    }

@Test
public void testGetTagName() {
    // Create an instance of TagInfoData
    TagInfoData tagInfoData = new TagInfoData();

    // Set the tag name
    String tagName = "Test Tag";
    tagInfoData.setTagName(tagName);

    // Call the getTagName() method
    String result = tagInfoData.getTagName();

    // Assert that the returned tag name is equal to the set tag name
    assertEquals(tagName, result);
}

}
