// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/oembed/OembedInformation_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:07:06 GMT 2024
 */
package org.jinstagram.entity.oembed;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.oembed.OembedInformation;
import org.junit.runner.RunWith;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.oembed.OembedInformation;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class OembedInformation_ESTest extends OembedInformation_ESTest_scaffolding {

    @Test
    public void testSetWidth() {
        OembedInformation oembed = new OembedInformation();
        String width = "100";
        oembed.setWidth(width);
        assertEquals(width, oembed.getWidth());
    }

    @Test
    public void testGetType() {
        // Create an instance of OembedInformation
        OembedInformation oembed = new OembedInformation();

        // Set the type using the setter method
        oembed.setType("video");

        // Get the type using the getType() method
        String type = oembed.getType();

        // Assert that the returned type is equal to the expected type
        assertEquals("video", type);
    }

    @Test
    public void testGetHtml() {
        OembedInformation oembed = new OembedInformation();
        String expectedHtml = "Test HTML";
        oembed.setHtml(expectedHtml);

        String actualHtml = oembed.getHtml();

        assertEquals(expectedHtml, actualHtml);
    }

    @Test
    public void testSetThumbnailWidth() {
        OembedInformation oembed = new OembedInformation();
        int thumbnailWidth = 100;
        oembed.setThumbnailWidth(thumbnailWidth);
        assertEquals(thumbnailWidth, oembed.getThumbnailWidth());
    }

    @Test
    public void testGetUrl() {
        OembedInformation oembed = new OembedInformation();
        String expectedUrl = "https://example.com";
        oembed.setUrl(expectedUrl);

        String actualUrl = oembed.getUrl();

        assertEquals(expectedUrl, actualUrl);
    }

    @Test
    public void testGetHeight() {
        OembedInformation oembed = new OembedInformation();
        String expectedHeight = "100";
        oembed.setHeight(expectedHeight);
        
        String actualHeight = oembed.getHeight();
        
        assertEquals(expectedHeight, actualHeight);
    }

    @Test
    public void testSetAuthorUrl() {
        OembedInformation oembed = new OembedInformation();
        String authorUrl = "https://example.com/author";

        oembed.setAuthorUrl(authorUrl);

        assertEquals(authorUrl, oembed.getAuthorUrl());
    }

    @Test
    public void testSetType() {
        OembedInformation oembed = new OembedInformation();
        String type = "video";
        oembed.setType(type);
        assertEquals(type, oembed.getType());
    }

    @Test
    public void testSetTitle() {
        OembedInformation oembed = new OembedInformation();
        String title = "Test Title";
        oembed.setTitle(title);
        assertEquals(title, oembed.getTitle());
    }

    @Test
    public void testSetHtml() {
        OembedInformation oembed = new OembedInformation();
        String html = "test html";

        oembed.setHtml(html);

        assertEquals(html, oembed.getHtml());
    }

    @Test
    public void testSetProviderName() {
        OembedInformation oembed = new OembedInformation();
        String providerName = "Test Provider";

        oembed.setProviderName(providerName);

        assertEquals(providerName, oembed.getProviderName());
    }

    @Test
    public void testGetProviderName() {
        OembedInformation oembed = new OembedInformation();
        String expectedProviderName = "Test Provider";
        oembed.setProviderName(expectedProviderName);

        String actualProviderName = oembed.getProviderName();

        assertEquals(expectedProviderName, actualProviderName);
    }

    @Test
    public void testGetThumbnailHeight() {
        OembedInformation oembed = new OembedInformation();
        int expectedHeight = 100;
        oembed.setThumbnailHeight(expectedHeight);

        int actualHeight = oembed.getThumbnailHeight();

        assertEquals(expectedHeight, actualHeight);
    }

    @Test
    public void testGetProviderUrl() {
        // Create an instance of OembedInformation
        OembedInformation oembed = new OembedInformation();

        // Set the provider URL
        String providerUrl = "https://example.com";
        oembed.setProviderUrl(providerUrl);

        // Get the provider URL using the getProviderUrl() method
        String actualProviderUrl = oembed.getProviderUrl();

        // Assert that the actual provider URL matches the expected provider URL
        assertEquals(providerUrl, actualProviderUrl);
    }

    @Test
    public void testGetMediaId() {
        OembedInformation oembed = new OembedInformation();
        String mediaId = "12345";
        oembed.setMediaId(mediaId);
        
        String result = oembed.getMediaId();
        
        assertEquals(mediaId, result);
    }

    @Test
    public void testGetThumbnailUrl() {
        OembedInformation oembed = new OembedInformation();
        String expectedThumbnailUrl = "https://example.com/thumbnail.jpg";
        oembed.setThumbnailUrl(expectedThumbnailUrl);

        String actualThumbnailUrl = oembed.getThumbnailUrl();

        assertEquals(expectedThumbnailUrl, actualThumbnailUrl);
    }

    @Test
    public void testGetVersion() {
        OembedInformation oembed = new OembedInformation();
        String expectedVersion = "1.0";
        oembed.setVersion(expectedVersion);

        String actualVersion = oembed.getVersion();

        assertEquals(expectedVersion, actualVersion);
    }

    @Test
    public void testSetProviderUrl() {
        OembedInformation oembed = new OembedInformation();
        String providerUrl = "https://example.com";
        oembed.setProviderUrl(providerUrl);
        assertEquals(providerUrl, oembed.getProviderUrl());
    }

    @Test
    public void testGetTitle() {
        OembedInformation oembed = new OembedInformation();
        String expectedTitle = "Test Title";
        oembed.setTitle(expectedTitle);

        String actualTitle = oembed.getTitle();

        assertEquals(expectedTitle, actualTitle);
    }

    @Test
    public void testGetThumbnailWidth() {
        OembedInformation oembed = new OembedInformation();
        int expectedWidth = 100;
        oembed.setThumbnailWidth(expectedWidth);

        int actualWidth = oembed.getThumbnailWidth();

        assertEquals(expectedWidth, actualWidth);
    }

    @Test
    public void testSetHeight() {
        OembedInformation oembed = new OembedInformation();
        String height = "100";

        oembed.setHeight(height);

        assertEquals(height, oembed.getHeight());
    }

    @Test
    public void testSetThumbnailUrl() {
        OembedInformation oembed = new OembedInformation();
        String thumbnailUrl = "https://example.com/thumbnail.jpg";
        
        oembed.setThumbnailUrl(thumbnailUrl);
        
        assertEquals(thumbnailUrl, oembed.getThumbnailUrl());
    }

    @Test
    public void testSetUrl() {
        OembedInformation oembed = new OembedInformation();
        String url = "https://example.com";
        oembed.setUrl(url);
        assertEquals(url, oembed.getUrl());
    }

    @Test
    public void testSetAuthorName() {
        OembedInformation oembed = new OembedInformation();
        String authorName = "John Doe";
        oembed.setAuthorName(authorName);
        assertEquals(authorName, oembed.getAuthorName());
    }

    @Test
    public void testSetVersion() {
        OembedInformation oembed = new OembedInformation();
        String version = "1.0";
        oembed.setVersion(version);
        assertEquals(version, oembed.getVersion());
    }

    @Test
    public void testGetAuthorUrl() {
        // Create an instance of OembedInformation
        OembedInformation oembed = new OembedInformation();

        // Set the authorUrl using the setter method
        oembed.setAuthorUrl("https://example.com/author");

        // Call the getAuthorUrl method and assert the expected value
        assertEquals("https://example.com/author", oembed.getAuthorUrl());
    }

@Test
public void testToString() {
    OembedInformation oembed = new OembedInformation();
    oembed.setProviderUrl("https://example.com");
    oembed.setTitle("Test Title");
    oembed.setUrl("https://example.com/test");
    oembed.setAuthorName("John Doe");
    oembed.setHeight("100");
    oembed.setWidth("200");
    oembed.setVersion("1.0");
    oembed.setAuthorUrl("https://example.com/author");
    oembed.setProviderName("Example Provider");
    oembed.setType("video");
    oembed.setMediaId("12345");

    String expected = "OembedInformation [provider_url=https://example.com, title=Test Title, url=https://example.com/test, author_name=John Doe, height=100, width=200, version=1.0, author_url=https://example.com/author, provider_name=Example Provider, type=video, mediaId=12345]";
    String actual = oembed.toString();

    assertEquals(expected, actual);
}

    @Test
    public void testGetAuthorName() {
        // Create an instance of OembedInformation
        OembedInformation oembed = new OembedInformation();

        // Set the author name
        oembed.setAuthorName("John Doe");

        // Get the author name using the getAuthorName() method
        String authorName = oembed.getAuthorName();

        // Assert that the returned author name is equal to the set author name
        assertEquals("John Doe", authorName);
    }

    @Test
    public void testSetThumbnailHeight() {
        OembedInformation oembed = new OembedInformation();
        int thumbnailHeight = 100;
        oembed.setThumbnailHeight(thumbnailHeight);
        assertEquals(thumbnailHeight, oembed.getThumbnailHeight());
    }

    @Test
    public void testGetWidth() {
        OembedInformation oembed = new OembedInformation();
        String expectedWidth = "100";
        oembed.setWidth(expectedWidth);

        String actualWidth = oembed.getWidth();

        assertEquals(expectedWidth, actualWidth);
    }

    @Test
    public void testSetMediaId() {
        OembedInformation oembed = new OembedInformation();
        String mediaId = "12345";
        oembed.setMediaId(mediaId);
        assertEquals(mediaId, oembed.getMediaId());
    }

}
