// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testRemoveRepeatedCharacters() {
        // Create a Line object
        Line line = new Line();
        
        // Create TextChunk objects
        TextChunk textChunk1 = new TextChunk("Hello");
        TextChunk textChunk2 = new TextChunk("World");
        
        // Add TextChunk objects to the Line object
        line.addTextChunk(textChunk1);
        line.addTextChunk(textChunk2);
        
        // Define the expected result
        Line expected = new Line();
        expected.addTextChunk(new TextChunk("Helo"));
        expected.addTextChunk(new TextChunk("World"));
        
        // Call the removeRepeatedCharacters method
        Line result = Line.removeRepeatedCharacters(line, 'l', 2);
        
        // Assert the expected result with the actual result
        assertEquals(expected.getTextElements(), result.getTextElements());
    }
}
