// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {
    @Test
    public void testMerge() {
        // Create test objects
        RectangularTextContainer<String> container1 = new RectangularTextContainer<>(0, 0, 10, 10);
        RectangularTextContainer<String> container2 = new RectangularTextContainer<>(5, 5, 10, 10);
        
        // Set initial text elements
        List<String> textElements1 = new ArrayList<>();
        textElements1.add("Hello");
        container1.setTextElements(textElements1);
        
        List<String> textElements2 = new ArrayList<>();
        textElements2.add("World");
        container2.setTextElements(textElements2);
        
        // Merge containers
        RectangularTextContainer<String> mergedContainer = container1.merge(container2);
        
        // Verify merged text elements
        List<String> expectedTextElements = new ArrayList<>();
        expectedTextElements.add("World");
        expectedTextElements.add("Hello");
        
        assertEquals(expectedTextElements, mergedContainer.getTextElements());
    }
}
