// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testSqueeze() {
        // Create a TextChunk object for testing
        TextChunk textChunk = new TextChunk(0, 0, 100, 50);
        textChunk.add(new TextElement("aaa"));
        textChunk.add(new TextElement("bbb"));
        textChunk.add(new TextElement("ccc"));
        textChunk.add(new TextElement("ddd"));
        textChunk.add(new TextElement("eee"));

        // Test when c is 'a' and minRunLength is 2
        Character c = 'a';
        int minRunLength = 2;
        List<TextChunk> result = textChunk.squeeze(c, minRunLength);

        // Verify the result
        assertEquals(2, result.size());
        assertEquals("bbb", result.get(0).getText());
        assertEquals("cccddd", result.get(1).getText());

        // Test when c is 'e' and minRunLength is 3
        c = 'e';
        minRunLength = 3;
        result = textChunk.squeeze(c, minRunLength);

        // Verify the result
        assertEquals(1, result.size());
        assertEquals("aaabbbcccddd", result.get(0).getText());
    }
}
