// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
@Test
public void testEquals() {
    // Create TextChunk objects for testing
    TextChunk textChunk1 = new TextChunk(0, 0, 10, 10);
    TextChunk textChunk2 = new TextChunk(0, 0, 10, 10);
    TextChunk textChunk3 = new TextChunk(0, 0, 20, 20);
    TextChunk textChunk4 = new TextChunk(0, 0, 10, 10);
    textChunk4.add(new TextElement("Hello"));

    // Test when comparing with itself
    assertTrue(textChunk1.equals(textChunk1));

    // Test when comparing with null
    assertFalse(textChunk1.equals(null));

    // Test when comparing with different class object
    assertFalse(textChunk1.equals("Hello"));

    // Test when comparing with equal TextChunk object
    assertTrue(textChunk1.equals(textChunk2));

    // Test when comparing with TextChunk object having different textElements
    assertFalse(textChunk1.equals(textChunk3));

    // Test when comparing with TextChunk object having different textElements
    assertFalse(textChunk1.equals(textChunk4));
}
}
