/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:50:55 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Pagination;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Pagination_ESTest extends Pagination_ESTest_scaffolding {
    @Test 
    public void testSetNextMinId() { 
    Pagination pagination = new Pagination();
    pagination.setNextMinId("1");
    assertEquals("1", pagination.getNextMinId());
    }
    
    
    @Test 
    public void testSetNextMaxTagId() throws Exception { 
    Pagination pagination = new Pagination();
    pagination.setNextMaxTagId(null);
    assertEquals(null, pagination.getNextMaxTagId());
    }
    
    
    @Test 
    public void testSetNextMaxId() throws Exception { 
    Pagination pagination = new Pagination();
    pagination.setNextMaxId("1");
    assertEquals("1", pagination.getNextMaxId());
    }
    
    
    @Test 
    public void testSetMinTagId() { 
    Pagination pagination = new Pagination();
    pagination.setMinTagId("1");
    assertEquals("1", pagination.getMinTagId());
    }
    
}
