// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    


    
    
    
    @Test
    public void testSetTextElements() {
        // Create a Line object
        Line line = new Line();

        // Create a list of TextChunk elements
        List<TextChunk> newTextChunks = new ArrayList<>();
        newTextChunks.add(new TextChunk("Chunk 1"));
        newTextChunks.add(new TextChunk("Chunk 2"));

        // Set the new list of TextChunk elements using setTextElements method
        line.setTextElements(newTextChunks);

        // Verify that the textChunks field in the Line object has been updated
        assertEquals(newTextChunks, line.textChunks);
    }
}
