/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:34:16 GMT 2024
 */

package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Caption;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Caption_ESTest extends Caption_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Caption caption0 = new Caption();
      caption0.setText("5 ~jrEY>R{v}NL");
      String string0 = caption0.getText();
      assertEquals("5 ~jrEY>R{v}NL", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Caption caption0 = new Caption();
      caption0.setId("m}vDm=29J? ~>THdr");
      String string0 = caption0.getId();
      assertEquals("m}vDm=29J? ~>THdr", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Caption caption0 = new Caption();
      caption0.setId("");
      String string0 = caption0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Caption caption0 = new Caption();
      caption0.setCreatedTime("p;O-6clE/tECl:0.8H");
      String string0 = caption0.getCreatedTime();
      assertEquals("p;O-6clE/tECl:0.8H", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Caption caption0 = new Caption();
      String string0 = caption0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Caption caption0 = new Caption();
      String string0 = caption0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Caption caption0 = new Caption();
      caption0.setCreatedTime("");
      String string0 = caption0.getCreatedTime();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Caption caption0 = new Caption();
      FromTagData fromTagData0 = caption0.getFrom();
      assertNull(fromTagData0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Caption caption0 = new Caption();
      String string0 = caption0.getCreatedTime();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Caption caption0 = new Caption();
      FromTagData fromTagData0 = new FromTagData();
      caption0.setFrom(fromTagData0);
      FromTagData fromTagData1 = caption0.getFrom();
      assertNull(fromTagData1.getProfilePicture());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Caption caption0 = new Caption();
      caption0.setText("");
      String string0 = caption0.getText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Caption caption0 = new Caption();
      String string0 = caption0.toString();
      assertEquals("Caption [createdTime=null, from=null, id=null, text=null]", string0);
  }
}
