/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:53:50 GMT 2024
 */

package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.GridPosition;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.common.UsersInPhoto;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UsersInPhoto_ESTest extends UsersInPhoto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      User user0 = new User();
      usersInPhoto0.setUser(user0);
      User user1 = usersInPhoto0.getUser();
      assertNull(user1.getFullName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      GridPosition gridPosition0 = new GridPosition();
      usersInPhoto0.setPosition(gridPosition0);
      gridPosition0.setY(1.0);
      GridPosition gridPosition1 = usersInPhoto0.getPosition();
      assertSame(gridPosition1, gridPosition0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      GridPosition gridPosition0 = new GridPosition();
      usersInPhoto0.setPosition(gridPosition0);
      gridPosition0.setY((-1.0));
      GridPosition gridPosition1 = usersInPhoto0.getPosition();
      assertSame(gridPosition1, gridPosition0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      GridPosition gridPosition0 = new GridPosition();
      usersInPhoto0.setPosition(gridPosition0);
      GridPosition gridPosition1 = usersInPhoto0.getPosition();
      assertSame(gridPosition1, gridPosition0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      GridPosition gridPosition0 = new GridPosition();
      gridPosition0.setX(1.0);
      usersInPhoto0.setPosition(gridPosition0);
      GridPosition gridPosition1 = usersInPhoto0.getPosition();
      assertSame(gridPosition1, gridPosition0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      GridPosition gridPosition0 = usersInPhoto0.getPosition();
      assertNull(gridPosition0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      GridPosition gridPosition0 = new GridPosition();
      usersInPhoto0.setPosition(gridPosition0);
      gridPosition0.setX((-2400.5468931945843));
      GridPosition gridPosition1 = usersInPhoto0.getPosition();
      assertEquals(0.0, gridPosition1.getY(), 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      UsersInPhoto usersInPhoto0 = new UsersInPhoto();
      User user0 = usersInPhoto0.getUser();
      assertNull(user0);
  }
}
