// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testToString() {
        Line line = new Line();
        TextChunk textChunk1 = new TextChunk("TextChunk1");
        TextChunk textChunk2 = new TextChunk("TextChunk2");
        
        line.addTextChunk(textChunk1);
        line.addTextChunk(textChunk2);
        
        String expected = line.toString();
        String actual = super.toString().substring(0, super.toString().length() - 1) + ",chunks='" + textChunk1.getText() + "', '" + textChunk2.getText() + "']";
        
        assertEquals(expected, actual);
    }
}
