// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testMerge() {
        // Create TextElements for TextChunks
        TextElement textElement1 = new TextElement(10, 20, 30, 40, "Hello");
        TextElement textElement2 = new TextElement(15, 25, 35, 45, "World");

        // Create TextChunks
        TextChunk textChunk1 = new TextChunk(textElement1);
        TextChunk textChunk2 = new TextChunk(textElement2);

        // Merge the TextChunks
        TextChunk mergedChunk = textChunk1.merge(textChunk2);

        // Verify the merged TextChunk
        List<TextElement> expectedElements = new ArrayList<>();
        expectedElements.add(textElement1);
        expectedElements.add(textElement2);

        assertEquals(expectedElements, mergedChunk.getTextElements());
    }
}
