// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/SubscriptionsListResponse_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:05:11 GMT 2024
 */
package org.jinstagram.realtime;


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.realtime.SubscriptionsListResponse;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SubscriptionsListResponse_ESTest extends SubscriptionsListResponse_ESTest_scaffolding {

@Test
public void testGetMeta() {
    // Create a new instance of SubscriptionsListResponse
    SubscriptionsListResponse response = new SubscriptionsListResponse();

    // Create a new instance of Meta
    Meta meta = new Meta();
    // Set the desired values for the Meta object
    // 

    // Set the Meta object in the SubscriptionsListResponse
    response.setMeta(meta);

    // Call the getMeta() method and store the result
    Meta result = response.getMeta();

    // Assert that the result is not null
    assertNotNull(result);

    // Assert that the result is the same as the Meta object set earlier
    assertEquals(meta, result);
}

@Test
public void testSetMeta() {
    // Create a new instance of SubscriptionsListResponse
    SubscriptionsListResponse response = new SubscriptionsListResponse();

    // Create a new instance of Meta
    Meta meta = new Meta();

    // Set the values for the Meta object
    meta.setCode(200);
    meta.setErrorType("none");
    meta.setErrorMessage(null);

    // Call the setMeta method on the SubscriptionsListResponse object
    response.setMeta(meta);

    // Verify that the meta object is set correctly
    assertEquals(meta, response.getMeta());
}

}
