// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/Zappos_zappos-json/src/test/java/com/zappos/json/format/BigIntegerFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:33:42 GMT 2024
 */
package com.zappos.json.format;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.BigIntegerFormatter;
import com.zappos.json.format.ValueFormatter;
import java.math.BigInteger;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class BigIntegerFormatter_ESTest extends BigIntegerFormatter_ESTest_scaffolding {
    @Test
    public void testCast() {
        BigIntegerFormatter formatter = new BigIntegerFormatter();
        
        // Test case 1: Valid input
        Object obj1 = new BigInteger("123456789");
        BigInteger result1 = formatter.cast(obj1);
        assertEquals(new BigInteger("123456789"), result1);
        
        // Test case 2: Invalid input
        Object obj2 = "123456789";
        try {
            BigInteger result2 = formatter.cast(obj2);
            fail("Expected ClassCastException to be thrown");
        } catch (ClassCastException e) {
            // Exception expected
        }
    }
}
