// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.lang.reflect.Field;
import java.lang.reflect.Type;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testGetFirstGenericType() {
        // Create a test field
        Field field = null; // Replace null with the actual field

        // Test when types array is null
        Class<?> result = Reflections.getFirstGenericType(field);
        assertNull(result);

        // Test when types array is empty
        Class<?>[] emptyTypes = new Class<?>[0];
        field = createFieldWithGenericTypes(emptyTypes);
        result = Reflections.getFirstGenericType(field);
        assertNull(result);

        // Test when types array has elements
        Class<?>[] types = new Class<?>[] { Integer.class, String.class };
        field = createFieldWithGenericTypes(types);
        result = Reflections.getFirstGenericType(field);
        assertEquals(Integer.class, result);
    }
}
