/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:52:13 GMT 2024
 */

package org.jinstagram;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.locations.LocationInfo;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InstagramObject_ESTest extends InstagramObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MediaCommentResponse mediaCommentResponse0 = new MediaCommentResponse();
      // Undeclared exception!
      try { 
        mediaCommentResponse0.getAPILimitStatus();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jinstagram.http.APILimitUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LocationInfo locationInfo0 = new LocationInfo();
      // Undeclared exception!
      try { 
        locationInfo0.getRemainingLimitStatus();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jinstagram.http.APILimitUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MediaCommentResponse mediaCommentResponse0 = new MediaCommentResponse();
      Map<String, String> map0 = mediaCommentResponse0.getHeaders();
      assertNull(map0);
  }
}
