// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/MapUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:13:58 GMT 2024
 */
package org.jinstagram.utils;




import static org.mockito.Mockito.*;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.MapUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MapUtils_ESTest extends MapUtils_ESTest_scaffolding {
    


    
    
    
    @Test
    public void testDecodeAndAppendEntries() {
        Map<String, String> source = new HashMap<>();
        source.put("key1", "value1");
        source.put("key2", "value2");

        Map<String, String> target = new HashMap<>();

        MapUtils.decodeAndAppendEntries(source, target);

        assertEquals("Encoded key1", "key1", URLUtils.percentDecode(target.get(URLUtils.percentEncode("key1"))));
        assertEquals("Encoded value1", "value1", URLUtils.percentDecode(target.get(URLUtils.percentEncode("key1"))));
        assertEquals("Encoded key2", "key2", URLUtils.percentDecode(target.get(URLUtils.percentEncode("key2"))));
        assertEquals("Encoded value2", "value2", URLUtils.percentDecode(target.get(URLUtils.percentEncode("key2")));
    }
}
