// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/InstagramSubscription_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:59:46 GMT 2024
 */
package org.jinstagram.realtime;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.jinstagram.realtime.InstagramSubscription;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class InstagramSubscription_ESTest extends InstagramSubscription_ESTest_scaffolding {
    @Test
    public void testToString() {
        InstagramSubscription subscription = new InstagramSubscription();
        Map<String, String> params = new HashMap<>();
        params.put("callback", "https://example.com/callback");
        params.put("clientId", "1234567890");
        params.put("clientSecret", "secret");
        params.put("object", "user");
        params.put("objectId", "123");
        params.put("verifyToken", "token");
        params.put("aspect", "media");
        params.put("latitude", "37.7749");
        params.put("longitude", "-122.4194");
        params.put("radius", "1000");
        subscription.params = params;

        String expected = "InstagramSubscription [callback=https://example.com/callback,clientId=1234567890,clientSecret=secret,object=user,objectId=123,verifyToken=token,aspect=media,latitude=37.7749,longitude=-122.4194,radius=1000]";
        String actual = subscription.toString();

        assertEquals(expected, actual);
    }
}
