// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/MapUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:13:58 GMT 2024
 */
package org.jinstagram.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.MapUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MapUtils_ESTest extends MapUtils_ESTest_scaffolding {
    @Test
    public void testSort() {
        // Create a test map
        Map<String, String> map = new LinkedHashMap<>();
        map.put("key1", "value1");
        map.put("key3", "value3");
        map.put("key2", "value2");

        // Call the sort method
        Map<String, String> sortedMap = MapUtils.sort(map);

        // Verify the sorted map
        assertEquals("key1", sortedMap.keySet().toArray()[0]);
        assertEquals("value1", sortedMap.get("key1"));
        assertEquals("key2", sortedMap.keySet().toArray()[1]);
        assertEquals("value2", sortedMap.get("key2"));
        assertEquals("key3", sortedMap.keySet().toArray()[2]);
        assertEquals("value3", sortedMap.get("key3"));
    }
}
