// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentsFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:32:11 GMT 2024
 */
package org.jinstagram.entity.comments;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class MediaCommentsFeed_ESTest extends MediaCommentsFeed_ESTest_scaffolding {
@Test
public void testToString() {
    // Create a MediaCommentsFeed object
    MediaCommentsFeed mediaCommentsFeed = new MediaCommentsFeed();

    // Create a CommentData object
    CommentData commentData = new CommentData();
    commentData.setText("Test comment");

    // Create a Meta object
    Meta meta = new Meta();
    meta.setCount(1);

    // Set the CommentData and Meta objects in the MediaCommentsFeed object
    mediaCommentsFeed.setCommentDataList(List.of(commentData));
    mediaCommentsFeed.setMeta(meta);

    // Expected result
    String expected = "MediaCommentsFeed [commentDataList=[CommentData [text=Test comment]], meta=Meta [count=1]]";

    // Call the toString() method
    String result = mediaCommentsFeed.toString();

    // Assert the result
    assertEquals(expected, result);
}
}
