// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/FromTagData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:38:11 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class FromTagData_ESTest extends FromTagData_ESTest_scaffolding {

    @Test
    public void testGetId() {
        FromTagData fromTagData = new FromTagData();
        String expectedId = "testId";
        fromTagData.setId(expectedId);

        String actualId = fromTagData.getId();

        assertEquals(expectedId, actualId);
    }

    @Test
    public void testGetFullName() {
        FromTagData fromTagData = new FromTagData();
        String expectedFullName = "John Doe";
        fromTagData.setFullName(expectedFullName);

        String actualFullName = fromTagData.getFullName();

        assertEquals(expectedFullName, actualFullName);
    }

    @Test
    public void testSetFullName() {
        FromTagData fromTagData = new FromTagData();
        String fullName = "John Doe";
        fromTagData.setFullName(fullName);
        
        assertEquals(fullName, fromTagData.getFullName());
    }

    @Test
    public void testSetId() {
        FromTagData fromTagData = new FromTagData();
        String id = "12345";
        fromTagData.setId(id);
        
        assertEquals(id, fromTagData.getId());
    }

    @Test
    public void testGetProfilePicture() {
        FromTagData fromTagData = new FromTagData();
        String expectedProfilePicture = "https://example.com/profile.jpg";
        fromTagData.setProfilePicture(expectedProfilePicture);

        String actualProfilePicture = fromTagData.getProfilePicture();

        assertEquals(expectedProfilePicture, actualProfilePicture);
    }

    @Test
    public void testGetUsername() {
        FromTagData fromTagData = new FromTagData();
        fromTagData.setUsername("testUsername");

        String actualUsername = fromTagData.getUsername();
        String expectedUsername = "testUsername";

        assertEquals(expectedUsername, actualUsername);
    }

    @Test
    public void testSetUsername() {
        FromTagData fromTagData = new FromTagData();
        String username = "testUsername";
        
        fromTagData.setUsername(username);
        
        assertEquals(username, fromTagData.getUsername());
    }

    @Test
    public void testToString() {
        FromTagData fromTagData = new FromTagData();
        fromTagData.setFullName("John Doe");
        fromTagData.setId("12345");
        fromTagData.setProfilePicture("https://example.com/profile.jpg");
        fromTagData.setUsername("johndoe");

        String expected = "FromTagData [fullName=John Doe, id=12345, profilePicture=https://example.com/profile.jpg, username=johndoe]";
        String actual = fromTagData.toString();

        assertEquals(expected, actual);
    }

    @Test
    public void testSetProfilePicture() {
        // Given
        FromTagData fromTagData = new FromTagData();
        String profilePicture = "https://example.com/profile.jpg";

        // When
        fromTagData.setProfilePicture(profilePicture);

        // Then
        assertEquals(profilePicture, fromTagData.getProfilePicture());
    }

}
