// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Images_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:42:55 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.ImageData;
import org.jinstagram.entity.common.Images;
import org.junit.runner.RunWith;

import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.ImageData;
import org.jinstagram.entity.common.Images;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Images_ESTest extends Images_ESTest_scaffolding {

    @Test
    public void testGetStandardResolution() {
        Images images = new Images();
        ImageData standardResolution = new ImageData();
        images.setStandardResolution(standardResolution);

        ImageData retrievedStandardResolution = images.getStandardResolution();

        assertNotNull("Standard resolution should not be null", retrievedStandardResolution);
        // Additional assertions or verifications can be added here based on specific requirements
    }

    @Test
    public void testGetThumbnail() {
        Images images = new Images();
        ImageData thumbnail = new ImageData();
        images.setThumbnail(thumbnail);

        ImageData retrievedThumbnail = images.getThumbnail();

        assertNotNull("Thumbnail should not be null", retrievedThumbnail);
        // Add more specific assertions as needed
    }

    @Test
    public void testGetLowResolution() {
        Images images = new Images();
        ImageData imageData = new ImageData();
        images.setLowResolution(imageData);

        ImageData retrievedImageData = images.getLowResolution();

        assertNotNull("Low resolution image data should not be null", retrievedImageData);
    }

    @Test
    public void testSetLowResolution() {
        Images images = new Images();
        ImageData expectedLowResolution = new ImageData();
        
        images.setLowResolution(expectedLowResolution);
        
        ImageData actualLowResolution = images.getLowResolution();
        
        assertEquals(expectedLowResolution, actualLowResolution);
    }

    @Test
    public void testSetThumbnail() {
        Images images = new Images();
        ImageData thumbnail = new ImageData();
        
        images.setThumbnail(thumbnail);
        
        assertEquals(thumbnail, images.getThumbnail());
    }

    @Test
    public void testSetStandardResolution() {
        Images images = new Images();
        ImageData imageData = new ImageData();
        
        images.setStandardResolution(imageData);
        
        assertEquals(imageData, images.getStandardResolution());
    }

}
