/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:18:17 GMT 2024
 */

package org.jinstagram.entity.tags;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TagSearchFeed_ESTest extends TagSearchFeed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      LinkedList<TagInfoData> linkedList0 = new LinkedList<TagInfoData>();
      tagSearchFeed0.setTagList(linkedList0);
      List<TagInfoData> list0 = tagSearchFeed0.getTagList();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      LinkedList<TagInfoData> linkedList0 = new LinkedList<TagInfoData>();
      tagSearchFeed0.setTagList(linkedList0);
      TagInfoData tagInfoData0 = new TagInfoData();
      linkedList0.push(tagInfoData0);
      List<TagInfoData> list0 = tagSearchFeed0.getTagList();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      Meta meta0 = new Meta();
      tagSearchFeed0.setMeta(meta0);
      Meta meta1 = tagSearchFeed0.getMeta();
      assertEquals(0, meta1.getCode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      Meta meta0 = new Meta();
      meta0.setCode((-3046));
      tagSearchFeed0.setMeta(meta0);
      Meta meta1 = tagSearchFeed0.getMeta();
      assertSame(meta1, meta0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      List<TagInfoData> list0 = tagSearchFeed0.getTagList();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      Meta meta0 = tagSearchFeed0.getMeta();
      assertNull(meta0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      String string0 = tagSearchFeed0.toString();
      assertEquals("TagSearchFeed [meta=null, tagList=null]", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TagSearchFeed tagSearchFeed0 = new TagSearchFeed();
      Meta meta0 = new Meta();
      tagSearchFeed0.setMeta(meta0);
      meta0.setCode(1578);
      Meta meta1 = tagSearchFeed0.getMeta();
      assertEquals(1578, meta1.getCode());
  }
}
