// original test path: /Users/zhi/Documents/PH.D/Project/Testing/ChatTESTER/CodePackage/Prompt2Testing/repo_get/Four_project/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/CarouselMedia_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:26:18 GMT 2024
 */
package org.jinstagram.entity.users.feed;

import org.jinstagram.entity.common.Videos;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.junit.runner.RunWith;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.junit.runner.RunWith;

import org.jinstagram.entity.common.Images;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class CarouselMedia_ESTest extends CarouselMedia_ESTest_scaffolding {

    @Test
    public void testSetType() {
        // Create an instance of CarouselMedia
        CarouselMedia carouselMedia = new CarouselMedia();

        // Set the type using the setType method
        carouselMedia.setType("image");

        // Verify that the type has been set correctly
        assertEquals("image", carouselMedia.getType());
    }

    @Test
    public void testGetVideos() {
        // Create a CarouselMedia object
        CarouselMedia carouselMedia = new CarouselMedia();

        // Create a Videos object
        Videos videos = new Videos();

        // Set the Videos object in the CarouselMedia object
        carouselMedia.setVideos(videos);

        // Call the getVideos() method
        Videos result = carouselMedia.getVideos();

        // Assert that the returned Videos object is the same as the one set
        assertEquals(videos, result);
    }

    @Test
    public void testGetType() {
        // Create an instance of CarouselMedia
        CarouselMedia carouselMedia = new CarouselMedia();

        // Set the type using the setter method
        carouselMedia.setType("image");

        // Get the type using the getType() method
        String type = carouselMedia.getType();

        // Assert that the returned type is equal to the expected type
        assertEquals("image", type);
    }

    @Test
    public void testSetImages() {
        CarouselMedia carouselMedia = new CarouselMedia();
        Images images = new Images();

        carouselMedia.setImages(images);

        assertEquals(images, carouselMedia.getImages());
    }

    @Test
    public void testGetImages() {
        // Create a CarouselMedia object
        CarouselMedia carouselMedia = new CarouselMedia();

        // Create an Images object
        Images images = new Images();
        // Set the properties of the Images object
        // 

        // Set the Images object in the CarouselMedia object
        carouselMedia.setImages(images);

        // Call the getImages() method
        Images result = carouselMedia.getImages();

        // Assert that the returned Images object is not null
        assertNotNull(result);

        // Assert that the returned Images object is the same as the one set
        assertSame(images, result);
    }

    @Test
    public void testSetVideos() {
        // Create a new instance of CarouselMedia
        CarouselMedia carouselMedia = new CarouselMedia();

        // Create a new instance of Videos
        Videos videos = new Videos();

        // Set the videos using the setVideos method
        carouselMedia.setVideos(videos);

        // Verify that the videos are set correctly
        assertEquals(videos, carouselMedia.getVideos());
    }

}
