/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {

@Test(timeout = 4000)
public void test00() throws Throwable {
    Line line0 = new Line();
    line0.setTextElements((List<TextChunk>) null);
    List<TextChunk> list0 = line0.getTextElements();
    assertNull(list0);
}

@Test(timeout = 4000)
public void test01() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = new TextChunk(236.93358F, 0.0F, 0.0F, 0.0F);
    List<TextChunk> list0 = textChunk0.squeeze((Character) null, 339);
    line0.setTextElements(list0);
    line0.addTextChunk(textChunk0);
    line0.addTextChunk(0, textChunk0);
    assertEquals(236.93358F, line0.height, 0.01F);
}

@Test(timeout = 4000)
public void test02() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = new TextChunk(236.93358F, 0.0F, 0.0F, 0.0F);
    List<TextChunk> list0 = textChunk0.squeeze((Character) null, 339);
    line0.setTextElements(list0);
    line0.addTextChunk(textChunk0);
    line0.addTextChunk(0, textChunk0);
    assertEquals(236.93358F, line0.height, 0.01F);
}

@Test(timeout = 4000)
public void test03() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = new TextChunk(4684.6978F, 0.0F, 0.0F, (-1382.9923F));
    line0.addTextChunk(textChunk0);
    Character character0 = new Character('\'');
    Line line1 = Line.removeRepeatedCharacters(line0, character0, (-3689));
    assertEquals(4684.6978F, line0.y, 0.01F);
    assertTrue(line1.equals((Object) line0));
}

@Test(timeout = 4000)
public void test04() throws Throwable {
    Line line0 = new Line();
    TextChunk textChunk0 = new TextChunk(236.93358F, 0.0F, 0.0F, 0.0F);
    List<TextChunk> list0 = textChunk0.squeeze((Character) null, 339);
    line0.setTextElements(list0);
    line0.addTextChunk(textChunk0);
    line0.addTextChunk(0, textChunk0);
    assertEquals(236.93358F, line0.height, 0.01F);
}

}
